### PR TITLE
Bunch of improvements

### PR DESCRIPTION
**Pull request by harry-cpp**
Look at commit titles for a more detailed description of stuff done.

### CODE REVIEW

**Comment by luiscubal** [comment]
Some feedback regarding this pull request.

Does Gtk# really need the .dll.config? I was under the impression that Mono already shipped these for this library.

There seem to be some issues with inconsistent spacing. I was using tabs and some changes are using spaces. This makes the diffs look odd, but it's not a huge issue.

I'd rather not change the test application to use Gtk. Instead, I'd prefer this to be handled like in the XWT test projects, where there is a common library project that is backend-independent, and then one project per backend that initializes things properly. Just see how XWT does it.

`GetWidgth()` Does this actually work?

Other than that, this seems OK.

**Comment by harry-cpp** [comment]
> Does Gtk# really need the .dll.config?

It needs it, it's not for Gtk#, it's for Xwt(xwt calls some native gtk methods).

> There seem to be some issues with inconsistent spacing. I was using tabs and some changes are using spaces. This makes the diffs look odd, but it's not a huge issue.

Oh, sorry, I keep my MonoDevelop set to Visual Studio coding policy... I can change stuff to tabs if you want...
PS. you can add "?w=1" at end of URL to ignore tabs / spaces.

> I'd rather not change the test application to use Gtk. Instead, I'd prefer this to be handled like in the XWT test projects, where there is a common library project that is backend-independent, and then one project per backend that initializes things properly.

I put it to Gtk for 2 reasons:
1) Gtk works on all systems
2) the person downloading the widget will not have to download full xwt repo as well

If you still do want it changed, just say so and I'll change it, but I'll also have to include Xwt as submodule as well.

> GetWidgth() Does this actually work?

Yes, yes it does. 

I had to set it to that so that it wouldn't use the visible width, but instead the full width of the widget.  You can see that the line highlighter was stopping at the end of the visible width, that is when the bottom scrollbar would appear the highlighter wouldn't highlight anything on the right, but would instead stop midway.

**Comment by luiscubal** [comment]
> It needs it, it's not for Gtk#, it's for Xwt(xwt calls some native gtk methods).

Right. It can stay, then.

> I put it to Gtk for 2 reasons:
> 1) Gtk works on all systems

I meant having _two_ test projects. One for Gtk and another one for WPF. The Gtk project could be the default one.

> 2) the person downloading the widget will not have to download full xwt repo as well

Ah, I see. You replaced the submodules with the DLLs. Sure, that could work. Though I'd still like there to be a WPF sample. Is the Xwt.Wpf.dll that big?

> Yes, yes it does. 

I see what's going on, now. Please just rename it to `GetWidth`.

**Comment by harry-cpp** [comment]
> I see what's going on, now. Please just rename it to GetWidth.

Oh... I mistyped it.... ups...

> I meant having two test projects. One for Gtk and another one for WPF. The Gtk project could be the default one.

Okay, WPF and Gtk coming right up!!!

**Comment by harry-cpp** [comment]
I found that I broke something with one of the changes. I'll fix that up and update the PR.

**Comment by harry-cpp** [comment]
Ok, done.

**Comment by luiscubal** [comment]
Merged. Thank you.

**Comment by harry-cpp** [comment]
I forgot to delete the old test app, just noticed :|

Sorry will add a PR for it right away.

**Pull request merged**
